In [1]:
import pandas

In [3]:
dataset = pandas.read_csv("xyzcollege-cs-4thyear - Sheet1.csv")

In [4]:
dataset

name  hrs  marks
0  rahul    4     40
1   eric    6     60
2    tom    8     80
3   yash    3     30

In [6]:
y = dataset["marks"]

In [7]:
y

0    40
1    60
2    80
3    30
Name: marks, dtype: int64

In [9]:
x = dataset["hrs"]

In [17]:
x

0    4
1    6
2    8
3    3
Name: hrs, dtype: int64

In [18]:
type(x)

pandas.core.series.Series

In [21]:
type (x.values )

numpy.ndarray

In [22]:
x.values.shape

(4,)

In [26]:
X = x.values.reshape(4, 1)

In [28]:
X.shape

(4, 1)

In [29]:
X.ndim

2

In [30]:
X

array([[4],
       [6],
       [8],
       [3]], dtype=int64)

In [11]:
y

0    40
1    60
2    80
3    30
Name: marks, dtype: int64

In [12]:
x

0    4
1    6
2    8
3    3
Name: hrs, dtype: int64

In [13]:
from sklearn.linear_model  import LinearRegression

In [14]:
# y = cx
model = LinearRegression()

In [31]:
# c = 10
# y=10x
model.fit(X , y )

LinearRegression()

In [33]:
dataset

name  hrs  marks
0  rahul    4     40
1   eric    6     60
2    tom    8     80
3   yash    3     30

In [35]:
# y = 10x
# y = 10 * 5
model.predict([[ 5 ]])

array([50.])

In [36]:
model.coef_

array([10.])

In [37]:
import joblib

In [38]:
joblib.dump(model , "mymarks.model")

['mymarks.model']